"""new fields in user model

Revision ID: 987e607585d2
Revises: 55c635b2b73c
Create Date: 2021-09-27 13:38:38.765282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '987e607585d2'
down_revision = '55c635b2b73c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
